/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IEpDArrowRight: typeof import('~icons/ep/d-arrow-right')['default']
    IEpInfoFilled: typeof import('~icons/ep/info-filled')['default']
    Rename: typeof import('./src/components/Rename.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
